development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: myapp

test:
  adapter: postgresql
  host: localhost
  port: 5432
  database: myapp_test
  username: postgres
  password: postgres